version: "2"
services:
    client:
        build:
            context: ./client/
            dockerfile: Dockerfile
        image: webapp-client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        networks:
            - webappnetwork
    api:
        build:
            context: ./api/
            dockerfile: Dockerfile
        image: webapp-api
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /api/node_modules
        networks:            
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge